// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

main(): Int64 {
    var 清风明月 = "11111"
    println("${清风明月}")
    println("prefix${清风明月}suffix")
    println("中文${清风明月}尾")
    println("😀${清风明月}")
    println("${清风明月}-${清风明月}")
    println("${清风明月 + 清风明月}")
    return 0
}
