// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package reExport.export

import reExport.export.funcs.foo1
private import reExport.export.funcs.foo2
internal import reExport.export.funcs.foo3
protected import reExport.export.funcs.foo4
public import reExport.export.funcs.foo5 as foo6